### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [hil-mr/time-editor#1]
Please fix Plugin home page https://hil.hessen.de/, it should reference a page dedicated to the plugin documentation and if you do not have rather use the README in the repo

**Comment by OSHistory** [comment]
@NyakudyaA  Thank you for the fast start of the review process, very much appreciated.  I have changed the link in the `metadata.txt` and in our QGIS Repo account. Do I need to upload  a new version of the zip-File?

**Comment by NyakudyaA** [comment]
Yes, you need to upload a new zip, replace the one you have already uploaded

**Comment by OSHistory** [comment]
Thanks I uploaded a new zip with the changed metadata.txt and also started some documentation in README.md which is now linked from metadata.txt

**Comment by OSHistory** [comment]
Again many thanks for the quick approval, your help and fast replies. I will close this issue.
